# Generated by Django 4.1.5 on 2023-01-14 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stu_code", models.IntegerField()),
                ("stu_name", models.CharField(max_length=20)),
                ("stu_email", models.EmailField(max_length=30)),
                ("stu_money", models.IntegerField()),
            ],
        ),
    ]
